[versions]
android-gradle-plugin = "8.5.2"
desugar_jdk_libs_nio = "2.1.2"
kotlin = "2.0.21"
androidx-appcompat = "1.7.0"
slf4j = "2.0.16"
log4j = "2.24.0"
jline = "3.26.2"
shadow = "8.3.2"
disruptor = "4.0.0"
junit = "5.11.1"
lwjgl = "3.3.4"
joml = "1.10.8"
launch4j = "3.0.6"
graal-native = "0.10.3"
idea-ext = "1.1.9"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
desugar_jdk_libs_nio = { module = "com.android.tools:desugar_jdk_libs_nio", version.ref = "desugar_jdk_libs_nio" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
jul-to-slf4j = { group = "org.slf4j", name = "jul-to-slf4j", version.ref = "slf4j" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
log4j-slf4j-impl = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl", version.ref = "log4j" }
jansi-core = { group = "org.jline", name = "jansi-core", version.ref = "jline" }
jline-terminal-jni = { group = "org.jline", name = "jline-terminal-jni", version.ref = "jline" }
jline-terminal-ffm = { group = "org.jline", name = "jline-terminal-ffm", version.ref = "jline" }
jline-reader = { group = "org.jline", name = "jline-reader", version.ref = "jline" }
disruptor = { group = "com.lmax", name = "disruptor", version.ref = "disruptor" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
joml = { group = "org.joml", name = "joml", version.ref = "joml" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-assignment = { id = "org.jetbrains.kotlin.plugin.assignment", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
launch4j = { id = "edu.sc.seis.launch4j", version.ref = "launch4j" }
graal-native = { id = "org.graalvm.buildtools.native", version.ref = "graal-native" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "idea-ext" }

[bundles]
logging = [
    "slf4j"
]
logging-runtime = [
    "jul-to-slf4j",
    "log4j-core",
    "log4j-slf4j-impl"
]
jline = [
    #    "jline-terminal-jni",
    "jline-terminal-ffm",
    "jline-reader",
    "jansi-core"
]